language: c
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq ctags bison flex
  - sudo apt-get install -qq libz-dev
  - sudo apt-get install -qq libevent-dev
  - git clone 'https://github.com/approach0/fork-cppjieba.git' /home/`whoami`/cppjieba
  - git clone 'https://github.com/approach0/fork-indri.git' /home/`whoami`/indri
  - (cd /home/`whoami`/indri && chmod +x configure && ./configure && make)
script:
  - ./configure --indri-path=/home/`whoami`/indri
  - make
